### ISSUE TITLE
csv file decompression

### ISSUE THREAD

**Issue by Gipn0za** [iltrof/ykcmp#5]
Hello, I want to make a translated version for a nippon1 game, but after extracting the CSV file, I cannot output the file using this program based on the actual offset of the file header. The log only contains .........|.........|.........|.........|.........|.........|.........|.........|.........|.........|
[eve_0008a.csv](https://github.com/user-attachments/files/16010585/eve_0008a.csv)

**Comment by HirAhiraPpy** [comment]
![image](https://github.com/iltrof/ykcmp/assets/30306009/514778e2-8777-4fc1-a73f-f46fb635b1e6)
The 4-byte-field right behind YKCMP_V1 is compression method. In your example, 0x00000008 means that the content is compressed by LZ4, which is not supported by this tool (LZ77).
